apiVersion: apps/v1
kind: Deployment
metadata:
  name: telecom-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telecom
  template:
    metadata:
      labels:
        app: telecom
    spec:
      containers:
      - name: telecom-container
        image: sanidhyaydv/telecom-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000